# Generated by Django 5.2.10 on 2026-02-01 18:10

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(db_comment='Идентификатор', primary_key=True, serialize=False)),
                ('group_serial_number', models.IntegerField(db_comment='Порядковый номер группы действий')),
                ('group_name', models.TextField(db_comment='Имя набора групп')),
                ('action_serial_number', models.IntegerField(db_comment='Порядковый номер действия внутри группы')),
                ('name', models.TextField(db_comment='Название действия')),
                ('params1', models.TextField(blank=True, db_comment='Значение параметра 1', null=True)),
                ('params2', models.TextField(blank=True, db_comment='Значение параметра 2', null=True)),
                ('params3', models.TextField(blank=True, db_comment='Значение параметра 3', null=True)),
                ('params4', models.TextField(blank=True, db_comment='Значение параметра 4', null=True)),
                ('params5', models.TextField(blank=True, db_comment='Значение параметра 5', null=True)),
                ('params6', models.TextField(blank=True, db_comment='Значение параметра 6', null=True)),
                ('params7', models.TextField(blank=True, db_comment='Значение параметра 7', null=True)),
                ('params8', models.TextField(blank=True, db_comment='Значение параметра 8', null=True)),
                ('params9', models.TextField(blank=True, db_comment='Значение параметра 9', null=True)),
                ('params10', models.TextField(blank=True, db_comment='Значение параметра 10', null=True)),
            ],
            options={
                'db_table': 'campaign_stats"."action',
                'db_table_comment': 'Таблица действий, с указанием групп и справочников к которым они относятся',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_comment='Название группы')),
                ('group_serial_number', models.IntegerField(db_comment='Порядковый номер группы внутри набора групп')),
            ],
            options={
                'db_table': 'campaign_stats"."campaign_group',
                'db_table_comment': 'Группы кампаний',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yd_login', models.TextField(db_comment='Логин агентского кабинета Директа')),
                ('name', models.TextField(db_comment='Название кампании', unique=True)),
                ('started_at', models.DateTimeField(db_comment='Дата-время начала кампании')),
                ('ended_at', models.DateTimeField(db_comment='Дата-время окончания кампании')),
                ('user_id', models.IntegerField(db_comment='связь с юзером из БД dit-services')),
                ('created_at', models.DateTimeField(db_comment='Дата-время создания', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Дата-время последнего обновления', null=True)),
                ('to_delete', models.BooleanField(db_comment='Флаг, используемый для "мягкого" удаления глобальной кампании', default=False)),
            ],
            options={
                'db_table': 'campaign_stats"."global_campaign',
                'db_table_comment': 'глобальные кампании',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupSets',
            fields=[
                ('id', models.BigAutoField(db_comment='Идентификатор', primary_key=True, serialize=False)),
                ('group_set_serial_number', models.IntegerField(db_comment='Порядковый номер набора групп')),
                ('name', models.TextField(db_comment='Название набора групп')),
            ],
            options={
                'db_table': 'campaign_stats"."group_sets',
                'db_table_comment': 'Наборы групп внутри глобальной кампании',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_comment='Название продукта', unique=True)),
                ('ym_counter', models.TextField(db_comment='Номер счетчика яндекс метрики')),
                ('yd_login', models.TextField(db_comment='Логин агентского кабинета Директа (текущий)')),
                ('links', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=75), db_comment='Ссылки на продукт', size=None)),
                ('user_id', models.IntegerField(db_comment='связь с юзером из БД dit-services')),
                ('created_at', models.DateTimeField(db_comment='Дата-время создания', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Дата-время последнего обновления', null=True)),
                ('to_delete', models.BooleanField(db_comment='Флаг используемый для "мягкого" удаления продукта', default=False)),
            ],
            options={
                'db_table': 'campaign_stats"."product',
                'db_table_comment': 'Таблица продуктов',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(db_comment='Уникальный идентификатор', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_comment='Связь с юзером из БД dit-services')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_comment='Время создание заявки')),
                ('from_datetime', models.DateTimeField(db_comment='Дата-время начала периода')),
                ('to_datetime', models.DateTimeField(db_comment='Дата-время окончания периода')),
                ('filepath', models.TextField(blank=True, db_comment='Путь/ссылка к файлу отчёта', null=True)),
                ('previous_filepath', models.TextField(blank=True, db_comment='Путь/ссылка к файлу предыдущего отчёта', null=True)),
                ('to_delete', models.BooleanField(blank=True, db_comment='Флаг об удалении, выставляемый пользователем', default=False)),
            ],
            options={
                'db_table': 'campaign_stats"."report',
                'db_table_comment': 'Таблица отчётов',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SheetsForForming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organic', models.BooleanField(db_comment='Органический трафик')),
                ('separate_yd_campaigns', models.BooleanField(db_comment='Отдельно по каждой кампании в директе')),
                ('manually_created_groups', models.BooleanField(db_comment='Группы, сформированные вручную')),
                ('visited_pages', models.BooleanField(db_comment='Посещенные страницы')),
                ('age', models.BooleanField(db_comment='Возраст аудитории')),
                ('gender', models.BooleanField(db_comment='Пол аудитории')),
                ('long_term_interests', models.BooleanField(db_comment='Долгосрочные интересы аудитории')),
                ('geography', models.BooleanField(db_comment='География аудитории')),
                ('devices', models.BooleanField(db_comment='Устройства аудитории')),
            ],
            options={
                'db_table': 'campaign_stats"."sheets_for_forming',
                'db_table_comment': 'Таблица листов формирования для каждого отчёта',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecificationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_comment='Название справочника', unique=True)),
                ('user_id', models.IntegerField(db_comment='Связь с юзером из БД dit-services')),
                ('number', models.IntegerField(db_comment='Количество действий в справочнике')),
                ('created_at', models.DateTimeField(db_comment='Дата-время создания', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Дата-время последнего обновления', null=True)),
                ('to_delete', models.BooleanField(db_comment='Флаг, используемый для "мягкого" удаления справочника действий', default=False)),
            ],
            options={
                'db_table': 'campaign_stats"."specification_action',
                'db_table_comment': 'справочник действий',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecificationPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_comment='Связь с юзером из БД dit-services')),
                ('created_at', models.DateTimeField(db_comment='Дата-время создания', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Дата-время последнего обновления', null=True)),
                ('name', models.TextField(db_comment='Название справочника')),
                ('number', models.IntegerField(blank=True, db_comment='Количество целей в справочнике', null=True)),
                ('to_delete', models.BooleanField(db_comment='Флаг, используемый для "мягкого" удаления справочника целей', default=False)),
            ],
            options={
                'db_table': 'campaign_stats"."specification_purpose',
                'db_table_comment': 'справочник целей',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(db_comment='Уникальный идентификатор', primary_key=True, serialize=False)),
                ('name', models.TextField(db_comment='Название статуса')),
                ('description', models.TextField(blank=True, db_comment='Расширенное описание статуса', null=True)),
            ],
            options={
                'db_table': 'campaign_stats"."status',
                'db_table_comment': 'справочник статусов',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yd_campaign_serial_number', models.IntegerField(db_comment='Порядковый номер кампании яндекс директа в группу', default=1)),
                ('name', models.TextField(db_comment='Название кампании в директе')),
                ('yd_campaign_id', models.TextField(db_comment='Айди кампании в директе')),
            ],
            options={
                'db_table': 'campaign_stats"."yd_campaign',
                'db_table_comment': 'Таблица кампаний Яндекс Директа с разделением на группы внутри набора групп',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(db_comment='Идентификатор', primary_key=True, serialize=False)),
                ('group_serial_number', models.IntegerField(db_comment='Порядковый номер группы целей в справочнике')),
                ('purpose_serial_number', models.IntegerField(db_comment='Порядковый номер цели внутри группы')),
                ('purpose_id', models.TextField(db_comment='Айди цели (в яндекс метрике)')),
                ('ym_name', models.TextField(db_comment='Название цели в яндекс метрике')),
                ('final_name', models.TextField(db_comment='Финальное название цели (самостоятельно исправленное)')),
                ('group_name', models.TextField(db_comment='Имя группы целей')),
                ('purpose_specification', models.ForeignKey(db_comment='Айди справочника целей к которому принадлежит цель', on_delete=django.db.models.deletion.DO_NOTHING, to='products_report_generator_api.specificationpurpose')),
            ],
            options={
                'db_table': 'campaign_stats"."purpose',
                'db_table_comment': 'Таблица целей',
                'managed': True,
            },
        ),
    ]
