# Generated by Django 5.2.3 on 2025-09-04 08:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_pp', '0002_alter_okpd2codifier_id'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='intermediatedata',
            table_comment='Таблица мини-задач',
        ),
        migrations.AlterModelTableComment(
            name='metric',
            table_comment='Таблица для хранения метрик на сбор статистики ПП',
        ),
        migrations.AlterModelTableComment(
            name='okpd2',
            table_comment='Таблица для ОКПД2 кодов, cвязана отношением ManyToMany с таблицей Segment',
        ),
        migrations.AlterModelTableComment(
            name='process',
            table_comment='Таблица процесса (задания) на сбор статистики ПП в соответствии с переданными параметрами (okpd2_ids, region_ids, metrics) используется для добавления заданий на сбор статистики и выдачу результатов',
        ),
        migrations.AlterModelTableComment(
            name='segment',
            table_comment='Таблица для хранения имён пользовательских сегментов, связана отношением ManyToMany c таблицей OKPD2',
        ),
        migrations.RenameField(
            model_name='intermediatedata',
            old_name='okpd2_id',
            new_name='okpd2',
        ),
        migrations.RenameField(
            model_name='intermediatedata',
            old_name='process_id',
            new_name='process',
        ),
        migrations.RemoveField(
            model_name='process',
            name='regions_ids',
        ),
        migrations.RemoveField(
            model_name='process',
            name='writed',
        ),
        migrations.AddField(
            model_name='intermediatedata',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='okpd2codifier',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='region_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_comment='массив идентификаторов регионов', default=[1], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='информация о дате-времени последнего обновления поля', null=True),
        ),
        migrations.AlterField(
            model_name='intermediatedata',
            name='contracts_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='intermediatedata',
            name='offers_active',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='intermediatedata',
            name='offers_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.CharField(db_comment='Уникальное имя метрики (параметра) в соответствии с которым собирается статистика', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='okpd2',
            name='code',
            field=models.IntegerField(db_comment='ОКПД2-код'),
        ),
        migrations.AlterField(
            model_name='okpd2',
            name='description',
            field=models.TextField(db_comment='Имя (описание) ОКПД2-кода кодовое'),
        ),
        migrations.AlterField(
            model_name='okpd2codifier',
            name='code',
            field=models.TextField(db_comment='ОКПД2-код c портала поставщиков'),
        ),
        migrations.AlterField(
            model_name='okpd2codifier',
            name='description',
            field=models.TextField(db_comment='Имя (описание) ОКПД2-кода текстовое'),
        ),
        migrations.AlterField(
            model_name='okpd2codifier',
            name='parent_id',
            field=models.IntegerField(db_comment='Идентификатор родительского ОКПД2-кода, если == 0 значит данный код не имеет родителей'),
        ),
        migrations.AlterField(
            model_name='process',
            name='completed',
            field=models.IntegerField(db_comment='поле готовности процесса: -1 не принято в обработку; 0 обрабатывается; 1 обработано', default=-1),
        ),
        migrations.AlterField(
            model_name='process',
            name='data_file',
            field=models.URLField(db_comment='адрес файла в S3 хранилище', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='error_msg',
            field=models.TextField(db_comment='поле для хранения сообщений об ошибках сбора статистики', null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='metrics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_comment='массив метрик (параметров) сбора статистики', size=None),
        ),
        migrations.AlterField(
            model_name='process',
            name='okpd2_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_comment='массив идентификаторов ОКПД2', size=None),
        ),
        migrations.AlterField(
            model_name='process',
            name='progress',
            field=models.IntegerField(db_comment='прогресс обработки процесса, процент', default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_code',
            field=models.CharField(db_comment='Код региона с ПП', max_length=50),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(db_comment='Название региона', max_length=255),
        ),
        migrations.AlterField(
            model_name='regioncodifier',
            name='region_code',
            field=models.CharField(db_comment='Код региона', max_length=50),
        ),
        migrations.AlterField(
            model_name='regioncodifier',
            name='region_name',
            field=models.CharField(db_comment='Имя региона', max_length=255),
        ),
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.CharField(db_comment='Имя сегмента', max_length=255, unique=True),
        ),
    ]
