# Generated by Django 5.2.3 on 2025-09-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_pp', '0003_alter_intermediatedata_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okpd2',
            name='code',
            field=models.IntegerField(),
        ),
    ]
