# Generated by Django 5.2.3 on 2025-09-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_pp', '0004_alter_okpd2_code'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='okpd2codifier',
            table_comment='Таблица для хранения ОКПД2-кодов с описанием и метками (parent_id) на родительские ОКПД2-коды',
        ),
        migrations.AlterModelTableComment(
            name='region',
            table_comment='Таблица для хранения кодов и названий регионов с ПП, связана отношением OneToMany с таблицей RegionCodifier',
        ),
        migrations.AlterModelTableComment(
            name='regioncodifier',
            table_comment='Таблица для хранения названий регионов, связана отношением OneToMany с таблицей Region',
        ),
        migrations.AlterField(
            model_name='okpd2',
            name='code',
            field=models.IntegerField(db_comment='ссылка на запись таблицы okpd2_codifier'),
        ),
    ]
