# Generated by Django 5.2.3 on 2025-09-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_pp', '0005_alter_okpd2codifier_table_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intermediatedata',
            name='completed',
        ),
    ]
