# Generated by Django 5.2.3 on 2025-09-04 11:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_pp', '0006_remove_intermediatedata_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediatedata',
            name='completed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0, 0, 0], size=None),
            preserve_default=False,
        ),
    ]
