# Generated by Django 5.2.10 on 2026-02-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('django_app_name', models.CharField()),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
    ]
